/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Project' 
 * Target:  'Project' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "py32f0xx.h"



#endif /* RTE_COMPONENTS_H */
